# server端口
server:
  port: 8888
           
# erueka 客户端配置  
eureka:
  client:
    healthcheck:
      enabled: true #开启健康检查
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
 #   appname: config-server # 配置服务名 类似  application:name: green-admin  没有 后者优先级高

# mybatis配置配置xml路径
# mybatis:
#  mapper-locations: classpath*:mapper/*Mapper.xml
#  type-aliases-package: com.green.model
 
#  mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.green.model
  global-config:
    id-type: 3  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    refresh: true # 修改xml后自动更新 生产环境下不建议开启
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

#  datasource链接配置
spring:
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://qdm170159589.my3w.com/qdm170159589_db?useUnicode=true&characterEncoding=UTF8
     username: qdm170159589
     password: 12345678