# server端口
server:
  port: 8889
           
# erueka 客户端配置  
eureka:
  client:
    healthcheck:
      enabled: true #开启健康检查
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
 #   appname: config-server # 配置服务名 类似  application:name: green-admin  没有 后者优先级高

# mybatis配置配置xml路径
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.green.model

#  datasource链接配置
spring:
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://qdm170159589.my3w.com/qdm170159589_db?useUnicode=true&characterEncoding=UTF8
     username: qdm170159589
     password: 12345678