# server端口
server:
  port: 8080
      
# erueka 客户端配置  
eureka:
  instance:
    prefer-ip-address: true
  client:   
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 开启feign的负载功能   
feign:
  hystrix:
    enabled: true

# zuul路由功能    
zuul:
  routes:
    api-a:
      path: /admin/**
      serviceId: green-admin